#!/usr/bin/python -E
#
# Copyright 2007 Google Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

"""Executable frontend to nss_cache."""

__author__ = ('jaq@google.com (Jamie Wilkinson)',
              'vasilios@google.com (Vasilios Hoffman)')

import logging
import os
import shutil
import sys
import tempfile

from nss_cache import app

if __name__ == '__main__':
  old_dir = os.getcwd()
  tempdir = tempfile.mkdtemp(prefix='nsscache')
  os.chdir(tempdir)
  nsscache_app = app.NssCacheApp()
  return_value = nsscache_app.Run(sys.argv[1:], os.environ)
  nsscache_app.log.info('Exiting nsscache with value %d', return_value)
  os.chdir(old_dir)
  shutil.rmtree(tempdir)
  sys.exit(return_value)
