#!/usr/bin/python2.4 -E
#
# Copyright 2007 Google Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

"""Executable frontend to nss_cache."""

__author__ = ('jaq@google.com (Jamie Wilkinson)',
              'vasilios@google.com (Vasilios Hoffman)')

import os
import sys
import traceback

from nss_cache import app

if __name__ == '__main__':
  try:
    app = app.NssCacheApp()
    return_value = app.Run(sys.argv[1:], os.environ)
  except:
    for line in traceback.format_exception(*sys.exc_info()):
      app.log.critical(line.rstrip('\n'))
    raise

  app.log.info('Exiting nsscache')
  app.log.debug('with value %d', return_value)
  sys.exit(return_value)
